/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik3;

import com.klinik3.query.Query;
import com.klinik3.bean.Obat;
import com.klinik3.util.NewHibernateUtil;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author albi
 */
public class fobat extends javax.swing.JInternalFrame {

Query q = new Query();
    /**
     * Creates new form Obat
     */
    public fobat() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkdobat = new javax.swing.JTextField();
        txtnmo = new javax.swing.JTextField();
        cjo = new javax.swing.JComboBox();
        tglobat = new com.toedter.calendar.JDateChooser();
        txthrg = new javax.swing.JTextField();
        bntsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(520, 275));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(520, 475));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Obat");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kode Obat");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama Obat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Obat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Kadaluarsa");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Harga Obat");

        txtkdobat.setPreferredSize(new java.awt.Dimension(200, 28));

        txtnmo.setPreferredSize(new java.awt.Dimension(300, 28));

        cjo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--PILIH--", "Kapsul", "Tablet", "Cair" }));

        tglobat.setPreferredSize(null);

        txthrg.setPreferredSize(null);

        bntsimpan.setText("Simpan");
        bntsimpan.setPreferredSize(new java.awt.Dimension(75, 28));
        bntsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.setPreferredSize(new java.awt.Dimension(75, 28));
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.setPreferredSize(new java.awt.Dimension(75, 28));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.setPreferredSize(new java.awt.Dimension(75, 28));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtkdobat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtnmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cjo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(tglobat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txthrg, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(bntsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(txtkdobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(txtnmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(cjo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(tglobat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addComponent(txthrg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntsimpanActionPerformed
      simpan();
    }//GEN-LAST:event_bntsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        ubah(); 
    }//GEN-LAST:event_btnubahActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        cari();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       hapus();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
bersih();    
    }//GEN-LAST:event_btnresetActionPerformed
public void hapus(){
    String kd = txtkdobat.getText();
q.hapuso(kd);
JOptionPane.showMessageDialog (null, "Berhasil dihapus", "Title", JOptionPane.INFORMATION_MESSAGE);
bersih();
}
public void bersih(){
txtkdobat.setText("");
txtnmo.setText("");
txthrg.setText("");
tglobat.setDate(null);
cjo.setSelectedIndex(0);
}
    public void cari(){
    Session session = NewHibernateUtil.getSessionFactory().openSession();
    try{
    String kd = txtkdobat.getText();
    Obat obat = (Obat) session.load(Obat.class, kd);
    txtnmo.setText(obat.getNmObat());
    
 String jo = obat.getJenisobat();
        System.out.println(jo);
 if (jo.equals("kapsul")){
 cjo.setSelectedIndex(1);
        }
  if (jo.equals("tablet")){
 cjo.setSelectedIndex(2);
        }
   if (jo.equals("cair")){
 cjo.setSelectedIndex(3);
        }
  String dateValue = obat.getTglkadaluarsa(); // What ever column
java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);

tglobat.setDate(date);
        txthrg.setText(obat.getHarga());
}catch (Exception E){
JOptionPane.showMessageDialog (null, "Data Tidak Ditemukan", "Title", JOptionPane.INFORMATION_MESSAGE);}
  bersih();

}
    public void simpan(){
String tampilan ="yyyy-MM-dd" ; 
SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
try{
String kdobat = txtkdobat.getText();

    String nmobat = txtnmo.getText();

    
       int pil1=0;

            String jo="";
      
            pil1 = cjo.getSelectedIndex();
            if (pil1==0) { jo="";}
            if (pil1==1) { jo="Kapsul";}
            if (pil1==2) { jo="Tablet";}
            if (pil1==3) { jo="Cair";}
           String tanggal = String.valueOf(fm.format(tglobat.getDate()));
            

    String hrg = txthrg.getText();
    System.out.println(kdobat);
    System.out.println(nmobat);
    System.out.println(jo);
    System.out.println(tanggal);
    System.out.println(hrg);
    q.tambaho(kdobat, nmobat, jo, tanggal, hrg);
    
    
    JOptionPane.showMessageDialog (null, "Berhasil Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
bersih();
}
catch (Exception E){
bersih();
}
    
    }
public void ubah(){
String tampilan ="yyyy-MM-dd" ; 
SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
try{
String kdobat = txtkdobat.getText();

    String nmobat = txtnmo.getText();

    
       int pil1=0;

            String jo="";
      
            pil1 = cjo.getSelectedIndex();
            if (pil1==0) { jo="";}
            if (pil1==1) { jo="Kapsul";}
            if (pil1==2) { jo="Tablet";}
            if (pil1==3) { jo="Cair";}
           String tanggal = String.valueOf(fm.format(tglobat.getDate()));
           String hrg = txthrg.getText();
    q.ubaho(kdobat, nmobat, jo, tanggal, hrg);
    
    
    JOptionPane.showMessageDialog (null, "Berhasil Diubah", "Title", JOptionPane.INFORMATION_MESSAGE);

}
catch (Exception E){

}
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntsimpan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox cjo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser tglobat;
    private javax.swing.JTextField txthrg;
    private javax.swing.JTextField txtkdobat;
    private javax.swing.JTextField txtnmo;
    // End of variables declaration//GEN-END:variables
}
