package com.klinik3.bean;
// Generated Nov 12, 2016 12:57:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Resep generated by hbm2java
 */
public class Resep  implements java.io.Serializable {


     private Integer index;
     private Dokter dokter;
     private Obat obat;
     private Pasien pasien;
     private String kdResep;
     private String jp;
     private Date tglresep;

    public Resep() {
    }

	
    public Resep(Dokter dokter, Pasien pasien, String kdResep, String jp, Date tglresep) {
        this.dokter = dokter;
        this.pasien = pasien;
        this.kdResep = kdResep;
        this.jp = jp;
        this.tglresep = tglresep;
    }
    public Resep(Dokter dokter, Obat obat, Pasien pasien, String kdResep, String jp, Date tglresep) {
       this.dokter = dokter;
       this.obat = obat;
       this.pasien = pasien;
       this.kdResep = kdResep;
       this.jp = jp;
       this.tglresep = tglresep;
    }
   
    public Integer getIndex() {
        return this.index;
    }
    
    public void setIndex(Integer index) {
        this.index = index;
    }
    public Dokter getDokter() {
        return this.dokter;
    }
    
    public void setDokter(Dokter dokter) {
        this.dokter = dokter;
    }
    public Obat getObat() {
        return this.obat;
    }
    
    public void setObat(Obat obat) {
        this.obat = obat;
    }
    public Pasien getPasien() {
        return this.pasien;
    }
    
    public void setPasien(Pasien pasien) {
        this.pasien = pasien;
    }
    public String getKdResep() {
        return this.kdResep;
    }
    
    public void setKdResep(String kdResep) {
        this.kdResep = kdResep;
    }
    public String getJp() {
        return this.jp;
    }
    
    public void setJp(String jp) {
        this.jp = jp;
    }
    public Date getTglresep() {
        return this.tglresep;
    }
    
    public void setTglresep(Date tglresep) {
        this.tglresep = tglresep;
    }




}


